#!/bin/bash

recursive=false

while getopts ":r" opt; do
  case $opt in
    r)
      recursive=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

if [ "$recursive" = true ]; then
  grep  -oPr '.*\{.*?\}' "$@"
else
  grep -oP '.*\{.*?\}' "$@"
fi

